name: Lucent

options:
  bundleIdPrefix: com.lucent
  deploymentTarget:
    iOS: "18.0"
    macOS: "15.0"

settings:
  base:
    SWIFT_VERSION: "6.0"
    MARKETING_VERSION: "1.0"
    CURRENT_PROJECT_VERSION: "1"
    ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS: YES
    ENABLE_USER_SCRIPT_SANDBOXING: YES

targets:
  Lucent (iOS):
    type: application
    platform: iOS
    sources:
      - path: Lucent/Shared
      - path: Lucent/iOS
    settings:
      base:
        PRODUCT_NAME: Lucent
        PRODUCT_BUNDLE_IDENTIFIER: com.lucent.app
        TARGETED_DEVICE_FAMILY: "1,2"
        IPHONEOS_DEPLOYMENT_TARGET: "18.0"
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown"
        INFOPLIST_KEY_NSFaceIDUsageDescription: "Lucent uses Face ID to securely protect your photos and prevent unauthorized access."
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        ENABLE_PREVIEWS: YES

  Lucent (macOS):
    type: application
    platform: macOS
    sources:
      - path: Lucent/Shared
      - path: Lucent/macOS
    settings:
      base:
        PRODUCT_NAME: Lucent
        PRODUCT_BUNDLE_IDENTIFIER: com.lucent.app
        MACOSX_DEPLOYMENT_TARGET: "15.0"
        GENERATE_INFOPLIST_FILE: YES
        ENABLE_HARDENED_RUNTIME: YES
        COMBINE_HIDPI_IMAGES: YES
        CODE_SIGN_ENTITLEMENTS: Lucent/macOS/Lucent.entitlements
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        ENABLE_PREVIEWS: YES

  LucentTests (iOS):
    type: bundle.unit-test
    platform: iOS
    sources:
      - LucentTests
    dependencies:
      - target: Lucent (iOS)
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.lucent.LucentTests
        IPHONEOS_DEPLOYMENT_TARGET: "18.0"
        TARGETED_DEVICE_FAMILY: "1,2"

  LucentTests (macOS):
    type: bundle.unit-test
    platform: macOS
    sources:
      - LucentTests
    dependencies:
      - target: Lucent (macOS)
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.lucent.LucentTests
        MACOSX_DEPLOYMENT_TARGET: "15.0"

  LucentUITests (iOS):
    type: bundle.ui-testing
    platform: iOS
    sources:
      - LucentUITests
    dependencies:
      - target: Lucent (iOS)
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.lucent.LucentUITests
        IPHONEOS_DEPLOYMENT_TARGET: "18.0"
        TARGETED_DEVICE_FAMILY: "1,2"
        TEST_TARGET_NAME: "Lucent (iOS)"

  LucentUITests (macOS):
    type: bundle.ui-testing
    platform: macOS
    sources:
      - LucentUITests
    dependencies:
      - target: Lucent (macOS)
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.lucent.LucentUITests
        MACOSX_DEPLOYMENT_TARGET: "15.0"
        TEST_TARGET_NAME: "Lucent (macOS)"

schemes:
  Lucent (iOS):
    build:
      targets:
        Lucent (iOS): all
        LucentTests (iOS): [test]
        LucentUITests (iOS): [test]
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - LucentTests (iOS)
        - LucentUITests (iOS)
    archive:
      config: Release

  Lucent (macOS):
    build:
      targets:
        Lucent (macOS): all
        LucentTests (macOS): [test]
        LucentUITests (macOS): [test]
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - LucentTests (macOS)
        - LucentUITests (macOS)
    archive:
      config: Release
